apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u74suml54-go 
  janus-idp.io/tekton: u74suml54-go
  backstage.io/kubernetes-id: u74suml54-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u74suml54-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  